services:
  - type: worker
    name: ai-vera-bot
    runtime: docker
    dockerfilePath: Dockerfile
    dockerCommand: python -m app.bot
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ADMIN_USER_IDS
        sync: false
      - key: PRO_USER_IDS
        sync: false
      - key: WHISPER_BACKEND
        value: "faster"
      - key: WHISPER_MODEL
        value: "small"
      - key: PRODAMUS_WEBHOOK_SECRET
        sync: false
      - key: PRODAMUS_PAYMENT_LINK
        sync: false
      - key: PRODAMUS_PRO_AMOUNT
        value: "299.0"
      - key: REDIS_URL
        sync: false
      - key: DATABASE_URL
        sync: false
