services:
  - type: worker
    name: ai-vera-bot-worker
    runtime: docker
    dockerfilePath: Dockerfile
    dockerCommand: python -m app.bot
    envVars:
      - key: PRO_USER_IDS
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ADMIN_USER_IDS
        sync: false
      - key: PRO_USER_IDS
        sync: false
      - key: PAYDMUS_WEBHOOK_SECRET
        sync: false
      - key: PAYDMUS_PRO_AMOUNT
        value: "299.0"
        - key: WHISPER_BACKEND       # "openai" или "faster"
        value: "faster"
      - key: WHISPER_MODEL         # для openai: base/small/...; для faster: small/medium/large-v3 и т.п.
        value: "small"
      - key: REDIS_URL             # опционально
        sync: false
      - key: DATABASE_URL          # опционально (postgres://... или postgresql://...)
        sync: false

  - type: web
    name: ai-vera-bot-web
    runtime: docker
    dockerfilePath: Dockerfile
    dockerCommand: python -m app.web
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ADMIN_USER_IDS
        sync: false
      - key: PRO_USER_IDS
        sync: false
      - key: PAYDMUS_WEBHOOK_SECRET
        sync: false
      - key: PAYDMUS_PRO_AMOUNT
        value: "299.0"
